apiVersion: batch/v1
kind: Job
metadata:
  name: your-app-name-cron-job
spec:
  template:
    spec:
      containers:
        - name: your-app-name-job
          image: registry.cn-hangzhou.aliyuncs.com/arexadmin01/arextest-plan-scheduler:0.6.5
          env:
            - name: APP_ID
              value: "your_app_id"
            - name: TARGET_HOST
              value: "your_target_host"
      restartPolicy: OnFailure